from backend.app import Song



def test_new_track():
    """
    GIVEN a Song model
    WHEN a new Song is created
    THEN check the id, name, and access_tokens fields are defined correctly
    """
    test_track = Song(
        party_id=1,
        name="not yet",
        artist="not yet",
        votes=0,
        uri="none",
        img_sm="none",
        img_md="medium",
        img_lg="lg",
        progress_ms=0,
        duration_ms=1000,
    )
    # assert test_track.id == 1, we don't check this becasue it is generated by the db? 
    assert test_track.name == "not yet"
    assert test_track.artist == "not yet"
    assert test_track.votes == 0
    assert test_track.uri == "none"
    assert test_track.img_sm == "none"
    assert test_track.img_md == "medium"
    assert test_track.img_lg == "lg"
    assert test_track.progress_ms == 0
    assert test_track.duration_ms == 1000
